"""Integration tests for the selector regeneration Celery task (Item 16).

Arrange-Act-Assert throughout. Runs against the Postgres testcontainer because
the task creates ``SelectorProfile`` rows with generated ids — SQLite does not
autoincrement a ``BigInteger`` primary key. The task body is invoked directly
with ``AsyncSessionLocal`` pointed at the test engine, so no broker or worker is
involved; the LLM is a Pydantic AI ``FunctionModel`` and no provider is contacted.

The behavioural contract under test: the task never raises, never retries, and
every non-promotion outcome is accounted for — either as a counted attempt
against the host's budget, or (for "generation disabled") explicitly *not*
counted, so a deployment with no key does not park every host as failed.
"""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from unittest.mock import patch

import pytest
from pydantic_ai import ModelResponse, TextPart, models
from pydantic_ai.models.function import FunctionModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import async_sessionmaker

from app.models.enums import ExtractionStatus, SelectorProfileStatus
from app.models.product import Product
from app.models.selector_profile import SelectorProfile
from app.schemas.scraper import ScrapedResult
from app.services import selector_profile_service
from app.services.llm import client as llm_client
from app.services.llm.client import selector_agent
from app.services.selector_generation import validate_selector
from app.tasks import selector as selector_task

models.ALLOW_MODEL_REQUESTS = False

pytestmark = pytest.mark.integration

_HOST = "shop.example.com"
_HTML = (
    "<html><body><h1>Widget</h1>"
    '<div id="buybox"><span class="pdp-price">£129.50</span></div></body></html>'
)


def _scraped(status: ExtractionStatus, html: str = _HTML) -> ScrapedResult:
    return ScrapedResult(
        url=f"https://{_HOST}/p/1",
        html=html,
        html_hash="hash",
        price=None,
        currency=None,
        scraped_at=datetime.now(UTC),
        extraction_status=status,
    )


def _model(payload: str) -> FunctionModel:
    """A model that always replies with *payload* as the structured output."""

    def respond(messages, info):  # noqa: ANN001, ARG001
        return ModelResponse(parts=[TextPart(content=payload)])

    return FunctionModel(respond)


def _exploding_model(message: str) -> FunctionModel:
    def explode(messages, info):  # noqa: ANN001, ARG001
        raise RuntimeError(message)

    return FunctionModel(explode)


def _forbidden_model() -> FunctionModel:
    def forbidden(messages, info):  # noqa: ANN001, ARG001
        raise AssertionError("the LLM must not be called on this path")

    return FunctionModel(forbidden)


@pytest.fixture()
async def session_factory(pg_engine, monkeypatch):
    """A session factory bound to the testcontainer, installed on the task module."""
    factory = async_sessionmaker(bind=pg_engine, expire_on_commit=False, autoflush=False)
    monkeypatch.setattr(selector_task, "AsyncSessionLocal", factory)
    return factory


@pytest.fixture()
async def product_id(session_factory) -> int:
    """A seeded product whose id is generated by the database."""
    async with session_factory() as session:
        product = Product(
            name="Widget",
            url=f"https://{_HOST}/p/1",
            source_type="generic",
            css_selector=".old-price",
        )
        session.add(product)
        await session.commit()
        return int(product.id)


@pytest.fixture()
def admin_llm(monkeypatch):
    monkeypatch.setattr(llm_client.settings, "LLM_PROVIDER", "openai")
    monkeypatch.setattr(llm_client.settings, "LLM_MODEL", "gpt-5.2")
    monkeypatch.setattr(llm_client.settings, "LLM_API_KEY", "sk-admin")


async def _profile(factory) -> SelectorProfile | None:
    async with factory() as session:
        return await session.scalar(select(SelectorProfile).where(SelectorProfile.host == _HOST))


async def _seed_profile(factory, **kwargs) -> None:
    defaults = {
        "host": _HOST,
        "source_type": "generic",
        "status": SelectorProfileStatus.STALE,
        "version": 0,
        "failed_attempts": 0,
    }
    defaults.update(kwargs)
    async with factory() as session:
        session.add(SelectorProfile(**defaults))
        await session.commit()


async def _run(product_id: int) -> str:
    """Invoke the task body directly, bypassing the Celery dispatch machinery."""
    return await selector_task.regenerate_selector.run(product_id)


class TestRegenerateSelectorHappyPath:
    async def test_validated_suggestion_is_promoted(self, session_factory, product_id, admin_llm):
        # Arrange
        payload = '{"price_selector": "#buybox .pdp-price", "confidence": 0.92}'

        # Act
        with patch.object(selector_task, "_refetch", return_value=_scraped(ExtractionStatus.OK)):
            with selector_agent.override(model=_model(payload)):
                outcome = await _run(product_id)

        # Assert
        assert outcome == "promoted"
        profile = await _profile(session_factory)
        assert profile is not None
        assert profile.status == SelectorProfileStatus.ACTIVE
        assert profile.price_selector == "#buybox .pdp-price"
        assert profile.version == 1
        assert profile.failed_attempts == 0
        assert profile.confidence == pytest.approx(0.92)
        assert profile.generated_by_provider == "openai"
        assert profile.generated_by_model == "gpt-5.2"
        assert profile.last_validated_at is not None

    async def test_promotion_clears_a_previous_failure_streak(
        self, session_factory, product_id, admin_llm
    ):
        # Arrange — a host part-way through its attempt budget
        await _seed_profile(session_factory, version=3, failed_attempts=2, detail="earlier failure")
        payload = '{"price_selector": "#buybox .pdp-price", "confidence": 0.8}'

        # Act
        with patch.object(selector_task, "_refetch", return_value=_scraped(ExtractionStatus.OK)):
            with selector_agent.override(model=_model(payload)):
                outcome = await _run(product_id)

        # Assert — healed: version bumped, budget reset
        assert outcome == "promoted"
        profile = await _profile(session_factory)
        assert profile.version == 4
        assert profile.failed_attempts == 0
        assert profile.detail is None

    async def test_promoted_selector_actually_extracts_the_page_price(
        self, session_factory, product_id, admin_llm
    ):
        # Arrange
        payload = '{"price_selector": "#buybox .pdp-price", "confidence": 0.9}'

        # Act
        with patch.object(selector_task, "_refetch", return_value=_scraped(ExtractionStatus.OK)):
            with selector_agent.override(model=_model(payload)):
                await _run(product_id)

        # Assert — an active profile is, by construction, a proven one
        profile = await _profile(session_factory)
        assert validate_selector(_HTML, profile.price_selector) == Decimal("129.50")


class TestRegenerateSelectorFailurePaths:
    async def test_unknown_product_is_a_no_op(self, session_factory):
        # Act
        outcome = await _run(999_999)

        # Assert
        assert outcome == "not_found"
        assert await _profile(session_factory) is None

    async def test_blocked_page_never_reaches_the_llm(self, session_factory, product_id, admin_llm):
        # Arrange — generating from a CAPTCHA page would store a selector for the
        # block interstitial and permanently poison the host
        # Act
        with patch.object(
            selector_task, "_refetch", return_value=_scraped(ExtractionStatus.CAPTCHA)
        ):
            with selector_agent.override(model=_forbidden_model()):
                outcome = await _run(product_id)

        # Assert
        assert outcome == "unusable_page"
        profile = await _profile(session_factory)
        assert profile.failed_attempts == 1
        assert profile.price_selector is None

    async def test_http_error_page_never_reaches_the_llm(
        self, session_factory, product_id, admin_llm
    ):
        # Act
        with patch.object(
            selector_task, "_refetch", return_value=_scraped(ExtractionStatus.HTTP_ERROR)
        ):
            with selector_agent.override(model=_forbidden_model()):
                outcome = await _run(product_id)

        # Assert
        assert outcome == "unusable_page"

    async def test_fetch_error_is_a_counted_attempt(self, session_factory, product_id, admin_llm):
        # Act
        with patch.object(selector_task, "_refetch", return_value=None):
            outcome = await _run(product_id)

        # Assert
        assert outcome == "unusable_page"
        assert (await _profile(session_factory)).failed_attempts == 1

    async def test_provider_error_is_a_counted_attempt(
        self, session_factory, product_id, admin_llm
    ):
        # Act — the provider times out / 500s / rejects the key
        with patch.object(selector_task, "_refetch", return_value=_scraped(ExtractionStatus.OK)):
            with selector_agent.override(model=_exploding_model("provider down")):
                outcome = await _run(product_id)

        # Assert — recorded and bounded, never raised out of the task
        assert outcome == "generation_failed"
        profile = await _profile(session_factory)
        assert profile.failed_attempts == 1
        assert "provider down" in (profile.detail or "")

    async def test_unvalidatable_selector_is_not_promoted(
        self, session_factory, product_id, admin_llm
    ):
        # Arrange — a hallucinated selector matching nothing on the page
        payload = '{"price_selector": ".ghost", "confidence": 0.99}'

        # Act
        with patch.object(selector_task, "_refetch", return_value=_scraped(ExtractionStatus.OK)):
            with selector_agent.override(model=_model(payload)):
                outcome = await _run(product_id)

        # Assert — the previous behaviour keeps serving; nothing unproven goes live
        assert outcome == "validation_failed"
        profile = await _profile(session_factory)
        assert profile.price_selector is None
        assert profile.status != SelectorProfileStatus.ACTIVE
        assert profile.failed_attempts == 1

    async def test_no_credential_does_not_burn_the_attempt_budget(
        self, session_factory, product_id, monkeypatch
    ):
        # Arrange — generation disabled deployment-wide
        monkeypatch.setattr(llm_client.settings, "LLM_API_KEY", "")

        # Act
        with patch.object(selector_task, "_refetch", return_value=_scraped(ExtractionStatus.OK)):
            outcome = await _run(product_id)

        # Assert — not this host's fault, so nothing is counted or parked
        assert outcome == "disabled"
        profile = await _profile(session_factory)
        assert profile.failed_attempts == 0
        assert profile.status != SelectorProfileStatus.FAILED

    async def test_exhausting_the_budget_parks_the_host_as_failed(
        self, session_factory, product_id, admin_llm, monkeypatch
    ):
        # Arrange — one attempt left
        monkeypatch.setattr(selector_profile_service.settings, "SELECTOR_MAX_REGEN_ATTEMPTS", 1)

        # Act
        with patch.object(selector_task, "_refetch", return_value=_scraped(ExtractionStatus.OK)):
            with selector_agent.override(model=_exploding_model("provider down")):
                await _run(product_id)

        # Assert — stops costing LLM calls until a user reports the issue
        assert (await _profile(session_factory)).status == SelectorProfileStatus.FAILED

    async def test_cooldown_short_circuits_a_duplicate_job(
        self, session_factory, product_id, admin_llm, monkeypatch
    ):
        # Arrange — several products on one host can each enqueue a job in the
        # same cycle; only the first may spend an attempt
        monkeypatch.setattr(selector_profile_service.settings, "SELECTOR_REGEN_COOLDOWN_HOURS", 6)
        await _seed_profile(session_factory, failed_attempts=1, last_attempt_at=datetime.now(UTC))

        # Act
        with selector_agent.override(model=_forbidden_model()):
            outcome = await _run(product_id)

        # Assert
        assert outcome == "cooldown"
        assert (await _profile(session_factory)).failed_attempts == 1

    async def test_refetch_returns_the_scraped_page(self, session_factory, product_id):
        # Arrange — _refetch is patched out elsewhere, so exercise it directly
        from app.models.product import Product

        async with session_factory() as session:
            product = await session.get(Product, product_id)
            profile = await selector_profile_service.get_or_create_profile(
                session, _HOST, "generic"
            )

            # Act
            with patch(
                "app.scrapers.generic.fetch_page",
                return_value=_scraped(ExtractionStatus.OK),
            ):
                result = await selector_task._refetch(session, product, profile, "generic")

        # Assert
        assert result is not None
        assert result.html == _HTML

    async def test_refetch_passes_the_previous_selector_through(self, session_factory, product_id):
        # Arrange — a stale-but-previously-healed host. GenericScraper refuses to
        # run with no selector at all, so without this the host could never be
        # re-fetched to generate a replacement.
        from app.models.product import Product

        async with session_factory() as session:
            product = await session.get(Product, product_id)
            product.css_selector = None
            profile = await selector_profile_service.get_or_create_profile(
                session, _HOST, "generic"
            )
            profile.price_selector = "#buybox .pdp-price"
            await session.flush()

            # Act
            with patch(
                "app.scrapers.generic.fetch_page",
                return_value=_scraped(ExtractionStatus.OK),
            ):
                result = await selector_task._refetch(session, product, profile, "generic")

        # Assert — the fetch reached the page rather than raising ScraperError
        assert result is not None

    async def test_refetch_swallows_a_scraper_error(self, session_factory, product_id):
        # Arrange — an unknown source type raises from the registry
        from app.models.product import Product

        async with session_factory() as session:
            product = await session.get(Product, product_id)
            profile = await selector_profile_service.get_or_create_profile(
                session, _HOST, "generic"
            )

            # Act
            result = await selector_task._refetch(session, product, profile, "no-such-source")

        # Assert — reported as a fetch failure, which the caller counts
        assert result is None

    async def test_failed_host_is_skipped_without_calling_the_llm(
        self, session_factory, product_id, admin_llm
    ):
        # Arrange — budget already spent
        await _seed_profile(session_factory, status=SelectorProfileStatus.FAILED, failed_attempts=9)

        # Act
        with selector_agent.override(model=_forbidden_model()):
            outcome = await _run(product_id)

        # Assert
        assert outcome == "cooldown"
